server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafe_db
    username: postgres
    password: adminPassword

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  access:
      key: 7#70OZn0#hgjv werstrdtrDsaodi98BK8C1%T&hBnrzgqK28o
      expiration-time: 7200000000
  refresh:
      key: 7787dsa8dp7#%7hftgvyyjhtfcttyik)*jk0OZ()BK8C1%Taskldjksal***
      expiration-time: 60480000000

app:
  admin:
    email: cafe_ad@gmail.com
    password: cafe_me@24
