name: Java CI with Maven

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/cafe-0.0.1-SNAPSHOT.jar'


      - name: Execute Jar File
        run: |
          sudo kill -9 $(sudo lsof -t -i:8090) || true
          sudo java -jar '${{ github.workspace }}/target/cafe-0.0.1-SNAPSHOT.jar' &
