name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
#      - name: Execute Jar File
#        run: |
#          sudo kill -9 $(sudo lsof -t -i:8090) || true
#          sudo java -jar /home/ubuntu/actions-runner/_work/cafe_b/cafe_b/target/cafe-0.0.1-SNAPSHOT.jar &

    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
