package com.example.cafe.utils;

import com.example.cafe.payload.api.ErrorData;

import java.util.ArrayList;
import java.util.List;

public interface MessageConstants {

    String NAME_REQUIRED = "NAME_REQUIRED";
    String DEFAULT_PAGE_REQUIRED = "DEFAULT_PAGE_REQUIRED";

    String ALREADY_EXISTS = "ALREADY_EXISTS";

    List<String> KEYS = new ArrayList<>() {{
        add(NAME_REQUIRED);
        add(DEFAULT_PAGE_REQUIRED);
        add(ALREADY_EXISTS);
    }};
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
    String ADMIN_ROLE_CAN_NOT_BE_DELETED = "ADMIN_ROLE_CAN_NOT_BE_DELETED";
    String PHONE_NUMBER_SHOULD_NOT_BLANK = "PHONE_NUMBER_SHOULD_NOT_BLANK";
    String NAME_SHOULD_NOT_BLANK = "NAME_SHOULD_NOT_BLANK";

    String PASSWORD_SHOULD_NOT_BLANK = "PASSWORD_SHOULD_NOT_BLANK";
    String FIRSTNAME_SHOULD_NOT_BLANK = "FIRSTNAME_SHOULD_NOT_BLANK";
    String TERMS_MUST_BE_ACCEPTED = "TERMS_MUST_BE_ACCEPTED";
    String EITHER_AREA_OR_IS_IFFY_AREA_SHOULD_HAVE = "EITHER_AREA_OR_IS_IFFY_AREA_SHOULD_HAVE";
    String EITHER_PRICE_OR_IS_NEGOTIABLE_SHOULD_HAVE = "EITHER_PRICE_OR_IS_NEGOTIABLE_SHOULD_HAVE";
    String SKILL_ALREADY_EXIST = "SKILL_ALREADY_EXIST";
    String USER_BLOCKED = "USER_BLOCKED";
    String FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED";
    String SUCCESSFULLY_ADDED = "SUCCESSFULLY_ADDED";
    String COMMENT_PUBLISHED = "COMMENT_PUBLISHED";
    String YOU_DO_NOT_HAVE_PERMISSION_TO_DELETE = "YOU_DO_NOT_HAVE_PERMISSION_TO_DELETE_THIS_WORK";
    String SUCCESSFULLY_DELETED = "SUCCESSFULLY_DELETED";
    String PROPOSAL_PAUSED = "PROPOSAL_PAUSED";
    String PROPOSAL_RESUMED = "PROPOSAL_RESUMED";
    String WORK_NOT_FOUND = "WORK_NOT_FOUND";
    String YOU_DO_NOT_CREATOR_OF_WORK = "YOU_DO_NOT_CREATOR_OF_WORK";
    String SUCCESSFULLY_EDITED = "SUCCESSFULLY_EDITED";
    String YOU_ARE_NOT_MASTER = "YOU_ARE_NOT_MASTER";
    String PROPOSAL_SENT = "PROPOSAL_SENT";
    String COMMENT_EDITED = "COMMENT_EDITED";
    String COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND";
    String YOU_DO_NOT_HAVE_PERMISSION_TO_EDIT = "YOU_DO_NOT_HAVE_PERMISSION_TO_EDIT";
    String EITHER_AVATAR_OR_BACKGROUND_IMAGE_SHOULD_HAVE = "AVATAR OR BG_IMAGE IS MISSING";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String SUCCESSFULLY_TOKEN_GENERATED = "SUCCESSFULLY_TOKEN_GENERATED";
    String CATEGORY_ALREADY_EXIST = "CATEGORY_ALREADY_EXIST";
    String PARENT_NOT_FOUND = "PARENT_NOT_FOUND";
    String CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
    String TABLE_ALREADY_EXIST = "TABLE_ALREADY_EXIST";
    String TABLE_NOT_FOUND = "TABLE_NOT_FOUND";
    String PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND";
    String PRODUCT_ALREADY_EXIST = "PRODUCT_ALREADY_EXIST";
    String DESCRIPTION_LENGTH_OVER_FLOW = "DESCRIPTION_LENGTH_OVER_FLOW";
    String MAIN_CATEGORY_NOT_FOUND = "MAIN_CATEGORY_NOT_FOUND";
    String ORDER_NOT_FOUND = "ORDER_NOT_FOUND";
    String LANGUAGE_NOT_FOUND = "LANGUAGE_NOT_FOUND";
}
